services:
  q-asker-mysql:
    image: mysql:latest
    container_name: q-asker-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - q-asker-db:/var/lib/mysql

  scouter-server:
    image: scouterapm/scouter-server:2.17.1
    container_name: scouter-server
    restart: no
    ports:
      - "6100:6100/tcp"
      - "6100:6100/udp"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - scouter-server-data:/home/scouter-server/database
    deploy:
      resources:
        limits:
          memory: 1024m

volumes:
  q-asker-db:
  scouter-server-data: