services:
  q-asker-mysql:
    image: mysql:latest
    container_name: q-asker-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - q-asker-db:/var/lib/mysql

  q-asker-redis:
    image: redis:latest
    container_name: q-asker-redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - q-asker-redis:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  q-asker-db:
  q-asker-redis: