services:
  app-blue:
    image: ${DOCKER_IMAGE}
    container_name: app-blue
    environment:
      - SPRING_PROFILES_ACTIVE=prod,blue
    ports:
      - "${BLUE_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app-green:
    image: ${DOCKER_IMAGE}
    container_name: app-green
    environment:
      - SPRING_PROFILES_ACTIVE=prod,green
    ports:
      - "${GREEN_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"