services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  scouter-server:
    image: scouterapm/scouter-server:2.17.1
    container_name: scouter-server
    restart: no
    ports:
      - "6100:6100/tcp"
      - "6100:6100/udp"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - scouter-server-data:/home/scouter-server/database
    deploy:
      resources:
        limits:
          memory: 1024m

volumes:
  scouter-server-data: